# The name given to the MariaDB/MySQL service (lowercase alphanumeric only).
db:
  # The type of your service (mysql), which uses the format
  # 'type:version'. Be sure to consult the MariaDB/MySQL documentation
  # (https://docs.platform.sh/configuration/services/mysql.html#supported-versions)
  # when choosing a version. If you specify a version number which is not available,
  # the CLI will return an error.
  type: mysql:10.5
  # The disk attribute is the size of the persistent disk (in MB) allocated to the service.
  disk: 2048